### PR TITLE
Updated License Date

### PR DESCRIPTION
**Pull request by blrhc**
For new year

### CODE REVIEW

**Comment by jipiboily** [comment]
Thanks!

PS: failed build but it's totally unrelated.

**Comment by jipiboily** [comment]
@ukd1 can I have commit access again or can you merge plz? :grinning:

**Comment by blrhc** [comment]
@ukd1, if you want to give me commit access as well then I can manage license updates more efficiently. I do that on lots of repos.

**Comment by jipiboily** [comment]
@ukd1 ping?

**Comment by ukd1** [comment]
@benhc123 this project is deprecated - we're not accepting any PR's for this. Thanks for the attempt though!

**Pull request closed without merging**
